version: '3'

networks:
  keycloak-network:
    external:
      name: keycloak-db
  ldap-network:
    external:
      name: ldap

services:
  keycloak:
    image: jboss/keycloak:12.0.2
    container_name: keycloak-export
    hostname: keycloak
    environment:
      KEYCLOAK_USER: keyadm
      KEYCLOAK_PASSWORD: k3Ycl0aK
      DB_VENDOR: mariadb
      DB_USER: keycloak
      DB_PASSWORD: k3Ycl0aK-mYsq1
      DB_DATABASE: keycloak
    volumes:
      - ./keycloak-provisioning:/data
    command: ['-b', '0.0.0.0', '-Dkeycloak.migration.action=export', '-Dkeycloak.migration.provider=dir', '-Dkeycloak.migration.dir=/data']
    ports:
      - 8080:8080
    networks:
      - keycloak-network
      - ldap-network
